sudo: false
language: ruby
env:
  - DB=sqlite3
rvm:
  - 2.2.3
before_install: gem install bundler -v 1.12.5
before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test
script: bundle exec rspec